 {
  defaults: {
    async: false,
    baseUrl: null,
    breaks: false,
    extensions: null,
    gfm: true,
    headerIds: true,
    headerPrefix: '',
    highlight: null,
    langPrefix: 'language-',
    mangle: true,
    pedantic: false,
    renderer: null,
    sanitize: false,
    sanitizer: null,
    silent: false,
    smartypants: false,
    tokenizer: null,
    walkTokens: null,
    xhtml: false
  },
  Lexer: [Function: Lexer] {
    lex: [Function: lex],
    lexInline: [Function: lexInline]
  },
  Parser: [Function: Parser] {
    parse: [Function: parse],
    parseInline: [Function: parseInline]
  },
  Renderer: [Function: Renderer],
  Slugger: [Function: Slugger],
  TextRenderer: [Function: TextRenderer],
  Tokenizer: [Function: Tokenizer],
  getDefaults: [Function: getDefaults],
  lexer: [Function: lex],
  marked: <ref *1> [Function: marked] {
    setOptions: [Function (anonymous)],
    options: [Function (anonymous)],
    getDefaults: [Function: getDefaults],
    defaults: {
      async: false,
      baseUrl: null,
      breaks: false,
      extensions: null,
      gfm: true,
      headerIds: true,
      headerPrefix: '',
      highlight: null,
      langPrefix: 'language-',
      mangle: true,
      pedantic: false,
      renderer: null,
      sanitize: false,
      sanitizer: null,
      silent: false,
      smartypants: false,
      tokenizer: null,
      walkTokens: null,
      xhtml: false
    },
    use: [Function (anonymous)],
    walkTokens: [Function (anonymous)],
    parseInline: [Function (anonymous)],
    Parser: [Function: Parser] {
      parse: [Function: parse],
      parseInline: [Function: parseInline]
    },
    parser: [Function: parse],
    Renderer: [Function: Renderer],
    TextRenderer: [Function: TextRenderer],
    Lexer: [Function: Lexer] {
      lex: [Function: lex],
      lexInline: [Function: lexInline]
    },
    lexer: [Function: lex],
    Tokenizer: [Function: Tokenizer],
    Slugger: [Function: Slugger],
    parse: [Circular *1]
  },
  options: [Function (anonymous)],
  parse: <ref *1> [Function: marked] {
    setOptions: [Function (anonymous)],
    options: [Function (anonymous)],
    getDefaults: [Function: getDefaults],
    defaults: {
      async: false,
      baseUrl: null,
      breaks: false,
      extensions: null,
      gfm: true,
      headerIds: true,
      headerPrefix: '',
      highlight: null,
      langPrefix: 'language-',
      mangle: true,
      pedantic: false,
      renderer: null,
      sanitize: false,
      sanitizer: null,
      silent: false,
      smartypants: false,
      tokenizer: null,
      walkTokens: null,
      xhtml: false
    },
    use: [Function (anonymous)],
    walkTokens: [Function (anonymous)],
    parseInline: [Function (anonymous)],
    Parser: [Function: Parser] {
      parse: [Function: parse],
      parseInline: [Function: parseInline]
    },
    parser: [Function: parse],
    Renderer: [Function: Renderer],
    TextRenderer: [Function: TextRenderer],
    Lexer: [Function: Lexer] {
      lex: [Function: lex],
      lexInline: [Function: lexInline]
    },
    lexer: [Function: lex],
    Tokenizer: [Function: Tokenizer],
    Slugger: [Function: Slugger],
    parse: [Circular *1]
  },
  parseInline: [Function (anonymous)],
  parser: [Function: parse],
  setOptions: [Function (anonymous)],
  use: [Function (anonymous)],
  walkTokens: [Function (anonymous)]
}
